Repository mehdy/keepalived-exporter, pull requests merged in 2020-06, with the labels that each got.

#20 Add _total postfix for counter metrics
  README.md
  internal/collector/collector.go
Labels: bug, enhancement

#23 ci: trigger ci for pull request events and use version matrix strategy for setuping go
  .github/workflows/go.yml
Labels: bug

#24 Fix Grafana dashboard metrics
  grafana/dashboards/keepalived-exporter.json
Labels: bug

#22 Fixed bug parsing text data | E.g. no VRID set, no Virtual IP info (keepalived_vrrp_state metric)
  internal/collector/parser.go
Labels: bug

#25 test: add a test to the project and setup the CI for it
  .github/workflows/go.yml
  Makefile
  internal/collector/collector.go
  internal/collector/parser.go
  internal/collector/parser_test.go
Labels: enhancement

#26 Add Github Actions badge
  README.md
Labels: documentation

#27 test: Add more tests for parser package
  internal/collector/collector.go
  internal/collector/parser.go
  internal/collector/parser_test.go
  internal/collector/setter.go
Labels: enhancement

#28 ci: add config for semantic bot
  .github/semantic.yml
Labels: enhancement

#29 test: add setter file tests
  internal/collector/setter_test.go
Labels: enhancement
