Repository mehdy/keepalived-exporter, pull requests merged in 2020-07, with the labels that each got.

#30 refactor: change default port to 9165
  README.md
  cmd/keepalived-exporter/main.go
Labels: documentation

#31 tests: add more parser tests
  internal/collector/collector.go
  internal/collector/parser.go
  internal/collector/parser_test.go
  internal/collector/setter.go
  internal/collector/setter_test.go
  test_files/keepalived.data
  test_files/keepalived.stats
Labels: bug, enhancement

#32 test: add collector tests
  internal/collector/collector.go
  internal/collector/collector_test.go
Labels: enhancement

#33 chore: update modules
  Makefile
  go.mod
  go.sum
Labels: enhancement

#34 docs: add installation methods to README.md
  README.md
Labels: documentation

#36 fix: parse interface from virtual ip
  internal/collector/collector.go
  internal/collector/parser.go
  internal/collector/parser_test.go
Labels: bug

#38 fix: support older array prop for keepalived data
  internal/collector/parser.go
  internal/collector/parser_test.go
  test_files/v2.0.10/keepalived.data
  test_files/v2.1.5/keepalived.data
  test_files/v2.1.5/keepalived.stats
Labels: bug

#39 fix: parse Virtual IP more than 5 chars
  internal/collector/parser.go
  internal/collector/parser_test.go
Labels: bug

#40 feat: add stderr to check script error logging
  internal/collector/collector.go
Labels: enhancement
