Repository mehdy/keepalived-exporter, pull requests merged in 2020-08, with the labels that each got.

#41 refactor: add more detail to sigNum error logging
  internal/collector/signal.go
Labels: enhancement

#48 build: Add version flag to show metadata info
  Makefile
  cmd/keepalived-exporter/main.go
Labels: enhancement

#51 fix: fixed a type in --help argument
  README.md
  cmd/keepalived-exporter/main.go
Labels: documentation

#49 build: remove v from version for make release command
  Makefile
Labels: bug

#50 feat: add support v1.3.5
  go.mod
  go.sum
  internal/collector/collector.go
  internal/collector/parser.go
  internal/collector/parser_test.go
  internal/collector/signal.go
  internal/collector/utils.go
  test_files/v1.3.5/keepalived.data
  test_files/v1.3.5/keepalived.stats
Labels: enhancement

#52 ci: add semantic conf to check all commits as well
  .github/semantic.yml
Labels: enhancement
