Repository mehdy/keepalived-exporter, pull requests merged in 2023-07, with the labels that each got.

#133 fix: add retry on errors for getKeepalivedStats
  internal/collector/collector.go
  internal/types/container/keepalived_container_collector_host.go
  internal/types/host/keepalived_host_collector_host.go
  internal/types/utils/files.go
  internal/types/utils/files_test.go
Labels: bug

#136 build: fix ldflags for goreleaser
  .goreleaser.yaml
Labels: build

#137 chore: update docker to v24.0.5
  .golangci-lint.yml
  Makefile
  go.mod
  go.sum
Labels: dependencies
