Repository mehdy/keepalived-exporter, pull requests merged in 2023-04, with the labels that each got.

#109 chore: update to go v1.20
  .github/workflows/go.yml
  Dockerfile
  Makefile
  go.mod
  go.sum
  internal/collector/parser.go
Labels: enhancement

#104 build: use goreleaser to build and publish new releases
  .github/workflows/release.yaml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yaml
  Makefile
  README.md
  deployments/release/Dockerfile
Labels: documentation, build, ci

#110 build: remove *.md from changelog filters
  .goreleaser.yaml
Labels: bug

#111 build: fix goreleaser issues
  .goreleaser.yaml
Labels: bug, build
